# Generated by Django 6.0.6 on 2026-09-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat', '0002_alter_chatmessage_options_alter_conversation_options_and_more'),
        ('projects', '0001_initial'),
        ('providers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requests_per_minute', models.PositiveIntegerField(default=20)),
                ('requests_per_day', models.PositiveIntegerField(default=500)),
                ('tokens_per_day', models.PositiveIntegerField(default=500000)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='providers.providerconfig')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('user__isnull', True), ('provider__isnull', True), _connector='OR'), name='quota_single_scope'), models.UniqueConstraint(condition=models.Q(('provider__isnull', True), ('user__isnull', True)), fields=('project',), name='quota_project'), models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('project', 'user'), name='quota_user'), models.UniqueConstraint(condition=models.Q(('provider__isnull', False)), fields=('project', 'provider'), name='quota_provider')],
            },
        ),
        migrations.CreateModel(
            name='UsageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('reserved', 'reserved'), ('success', 'success'), ('failed', 'failed')], default='reserved', max_length=20)),
                ('reserved_tokens', models.PositiveIntegerField()),
                ('input_tokens', models.PositiveIntegerField(default=0)),
                ('output_tokens', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.conversation')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='providers.providerconfig')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['project', 'created_at'], name='usage_usage_project_4a57a6_idx'), models.Index(fields=['project', 'user', 'created_at'], name='usage_usage_project_63ca11_idx')],
            },
        ),
    ]
