# Generated by Django 6.0.6 on 2026-09-25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("usage", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quota",
            name="group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quotas",
                to="projects.projectgroup",
            ),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="usage_records", to="projects.projectgroup"
            ),
        ),
        migrations.RemoveConstraint(model_name="quota", name="quota_single_scope"),
        migrations.RemoveConstraint(model_name="quota", name="quota_project"),
        migrations.AddConstraint(
            model_name="quota",
            constraint=models.CheckConstraint(
                condition=(
                    models.Q(("group__isnull", True), ("user__isnull", True))
                    | models.Q(("provider__isnull", True), ("user__isnull", True))
                    | models.Q(("group__isnull", True), ("provider__isnull", True))
                ),
                name="quota_single_scope",
            ),
        ),
        migrations.AddConstraint(
            model_name="quota",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("group__isnull", True),
                    ("provider__isnull", True),
                    ("user__isnull", True),
                ),
                fields=("project",),
                name="quota_project",
            ),
        ),
        migrations.AddConstraint(
            model_name="quota",
            constraint=models.UniqueConstraint(
                condition=models.Q(("group__isnull", False)),
                fields=("project", "group"),
                name="quota_group",
            ),
        ),
    ]
