# Generated by Django 6.0.6 on 2026-09-23 15:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField()),
                ('enabled', models.BooleanField(default=True)),
                ('allow_external', models.BooleanField(default=False)),
                ('external_max_classification', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Internal'), (2, 'Confidential'), (3, 'Restricted')], default=0)),
                ('default_classification', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Internal'), (2, 'Confidential'), (3, 'Restricted')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Editor'), (2, 'Administrator')], default=0)),
                ('clearance', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('can_use_external', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_memberships', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='projects.project')),
                ('groups', models.ManyToManyField(blank=True, related_name='memberships', to='projects.projectgroup')),
            ],
        ),
        migrations.CreateModel(
            name='AccessPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('minimum_role', models.PositiveSmallIntegerField(choices=[(0, 'Reader'), (1, 'Editor'), (2, 'Administrator')], default=0)),
                ('access_level', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('classification', models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Internal'), (2, 'Confidential'), (3, 'Restricted')], default=1)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='projects.project')),
                ('groups', models.ManyToManyField(blank=True, related_name='policies', to='projects.projectgroup')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='projects.tenant'),
        ),
        migrations.AddConstraint(
            model_name='projectgroup',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='group_project_name'),
        ),
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.UniqueConstraint(fields=('project', 'user'), name='membership_project_user'),
        ),
        migrations.AddIndex(
            model_name='accesspolicy',
            index=models.Index(fields=['project', 'access_level', 'minimum_role'], name='projects_ac_project_70e4c9_idx'),
        ),
        migrations.AddConstraint(
            model_name='project',
            constraint=models.UniqueConstraint(fields=('tenant', 'slug'), name='project_tenant_slug'),
        ),
    ]
