# Generated by Django 6.0.6 on 2026-09-23 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['created_at', 'id']},
        ),
        migrations.AlterModelOptions(
            name='conversation',
            options={'ordering': ['-updated_at', '-id']},
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='classification',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='source_document_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='conversation',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.project'),
        ),
        migrations.AddField(
            model_name='conversation',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['project', 'user', '-updated_at'], name='chat_conver_project_78fa8d_idx'),
        ),
    ]
