# Generated by Django 6.0.6 on 2026-09-23 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('enabled', models.BooleanField(default=True)),
                ('context_tokens', models.PositiveIntegerField(default=8192, validators=[django.core.validators.MinValueValidator(512), django.core.validators.MaxValueValidator(131072)])),
                ('max_output_tokens', models.PositiveIntegerField(default=512, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8192)])),
                ('supports_streaming', models.BooleanField(default=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.CreateModel(
            name='AgentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_prompt', models.TextField(default='You are a helpful assistant.')),
                ('rag_enabled', models.BooleanField(default=True)),
                ('top_k', models.PositiveSmallIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('max_context_chars', models.PositiveIntegerField(default=12000, validators=[django.core.validators.MinValueValidator(100), django.core.validators.MaxValueValidator(24000)])),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_config', to='projects.project')),
                ('fallback_model', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fallback_agents', to='providers.modelconfig')),
                ('primary_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='primary_agents', to='providers.modelconfig')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProviderConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField()),
                ('connection_alias', models.CharField(max_length=80)),
                ('enabled', models.BooleanField(default=True)),
                ('available', models.BooleanField(default=True, help_text='Administrative availability switch; failures are handled at execution.')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.AddField(
            model_name='modelconfig',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='providers.providerconfig'),
        ),
        migrations.AddConstraint(
            model_name='providerconfig',
            constraint=models.UniqueConstraint(fields=('project', 'name'), name='provider_project_name'),
        ),
        migrations.AddConstraint(
            model_name='modelconfig',
            constraint=models.UniqueConstraint(fields=('provider', 'name'), name='model_provider_name'),
        ),
    ]
